POST http://localhost:3000/products 
content-type: application/json

{
    "title": "Bag",
    "price": 300,
    "image":"uploads/bag.jpg"
}

###
GET http://localhost:3000/products?search=bag&page=1&limit=6

###
GET http://localhost:3000/products/697b1a7a7429f9aa52d4f748

###
PUT http://localhost:3000/products/697b1a7a7429f9aa52d4f748 
content-type: application/json

{
    "title": "IPhone 17",
    "price": 10000
}

###
DELETE  http://localhost:3000/products/6981c4859bf5d1a774497dfa

###
POST http://localhost:3000/orders 
content-type: application/json

{
    "productId": "697b3ea062317712c70139dc",
    "status": "Delievered"
}

###
GET http://localhost:3000/orders/697b58e462317712c70139f1

###
GET http://localhost:3000/orders

###
PUT http://localhost:3000/orders/697b3325908cbbc5246bd07d 
content-type: application/json

{
    "productId": "697b1a7a7429f9aa52d4f748",
    "status": "Shipped"
}

###
DELETE  http://localhost:3000/orders/697b3325908cbbc5246bd07d

###
POST http://localhost:3000/register 
content-type: application/json

{
    "name":"Manvi",
    "email": "manvi@gmail.com",
    "password": "manvi123",
    "role":"admin"
}

###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "akshit@gmail.com",
    "password": "akshit123"
}

###
GET http://localhost:3000/users?search=om&page=1&limit=7

###
GET http://localhost:3000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODVlNTQ2ZDc0ZWE5YmY2YzE3ZTI4YyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzcwMzgyODgzfQ.IJH6LC2Tzdo8ShPZKmFXDIh2dBKt9YvCycpk3g59tcw


