POST http://localhost:3000/products 
content-type: application/json

{
    "title": "Bag",
    "price": 300,
    "image":"uploads/bag.jpg"
}

###
GET http://localhost:3000/products?search=bag&page=1&limit=6

###
GET http://localhost:3000/products/697b1a7a7429f9aa52d4f748

###
PUT http://localhost:3000/products/698486d48da0a417e1b5a988 
content-type: application/json

{
    "title": "IPhone 17",
    "price": 10000
}

###
DELETE  http://localhost:3000/products/6981c4859bf5d1a774497dfa

###
POST http://localhost:3000/orders 
content-type: application/json

{
    "productId": "69841c999cd2e4901c829852",
    "quantity":2,
    "totalAmount":1000
}

###
GET http://localhost:3000/orders/697b58e462317712c70139f1

###
GET http://localhost:3000/orders?page=2&limit=2&search=top

###
PUT http://localhost:3000/orders/697b3325908cbbc5246bd07d 
content-type: application/json

{
    "productId": "697b1a7a7429f9aa52d4f748",
    "status": "Shipped"
}

###
DELETE  http://localhost:3000/orders/697b3325908cbbc5246bd07d

###
POST http://localhost:3000/register 
content-type: application/json

{
    "name":"Yugma",
    "email": "yugma@gmail.com",
    "password": "yugma123",
    "role":"user"
}

###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "admin123@gmail.com",
    "password": "admin123"
}

###
GET http://localhost:3000/users?search=om&page=1&limit=7

###
GET http://localhost:3000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODU3MzBmMGM0OWUzYjljOTQyN2Y1MyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MTgyMzE1NCwiZXhwIjoxNzcxODI2NzU0fQ.riXoRscpaWYYxHcN8WURuHuiEHCkMfR5UhHWiJAW2Kw


